CREATE TABLE SALESREP (
          REP_ID,FNAME,
          LNAME NOT NULL,
          PHONE_NUMBER,
          SALARY,
          COMMISSION,
          CONSTRAINT SALESREP_REP_ID_PK PRIMARY KEY(REP_ID),
          CONSTRAINT SALESREP_SALARY_CK CHECK(SALARY > 0)
          ) 
  AS(SELECT  EMPLOYEE_ID,
          FIRST_NAME, 
          LAST_NAME,
          PHONE_NUMBER,
          SALARY,
          COMMISSION_PCT
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 80);

SELECT * FROM SALESREP;    

DESCRIBE SALESREP;

drop table salesrep;

CREATE TABLE CUST
(CUST#       NUMBER(6),
 CUSTNAME    VARCHAR2(30) NOT NULL,
 CITY        VARCHAR2(20) NOT NULL,
 RATING      CHAR(1),
 COMMENTS    VARCHAR2(200),
 SALESREP#   NUMBER(7),
 CONSTRAINT CUST_CUST#_PK PRIMARY KEY(CUST#),
 CONSTRAINT CUST_CUSTNAME_CITY_UK UNIQUE(CUSTNAME, CITY),
 CONSTRAINT CUST_RATING_CK CHECK(RATING IN('A','B','C','D')),
 CONSTRAINT CUST_SALESREP#_FK FOREIGN KEY(SALESREP#)
            REFERENCES SALESREP(REP_ID)
);

DESCRIBE SALESREP;

DESCRIBE EMPLOYEES;

SELECT * FROM SALESREP;

INSERT INTO CUST VALUES (501, 'ABC LTD', 'Montreal', 'C', NULL, 149); 
INSERT INTO CUST values (502, 'BLACK GIANT', 'Ottawa', 'B', NULL, 174);
INSERT INTO CUST values (503, 'MOTHER GOOSE', 'London', 'B', NULL, 176);
INSERT INTO CUST  values (701, 'BLUE SKY LTD', 'Vancouver', 'B', NULL, 149); 
INSERT INTO CUST values (702, 'MIKE and SAM inc.', 'Kingston', 'A', NULL, 174);
INSERT INTO CUST values (703, 'RED PLANET', 'Mississauga', 'C', NULL, 176);
INSERT INTO CUST  values (717, 'BLUE SKY LTD', 'Regina', 'D', NULL, 149);


CREATE TABLE GOODCUST(
      CUST_ID,
      NAME NOT NULL,
      LOCATION,
      REP_ID,
      CONSTRAINT GOODCUST_CUST_ID_PK PRIMARY KEY(CUST_ID)
     -- CONSTRAINT GOODCUST_REP_ID_FK FOREIGN KEY(REP_ID)
     --           REFERENCES SALESREP(REP_ID))
  )AS(
      SELECT CUST#,
             CUSTNAME,
             CITY,
             SALESREP#
      FROM CUST
      WHERE RATING IN ('A','B'));
      
      SELECT * FROM GOODCUST;
      
ALTER TABLE GOODCUST
 ADD CONSTRAINT GOODCUST_REP_ID_FK FOREIGN KEY(REP_ID)
      REFERENCES SALESREP(REP_ID);

ALTER TABLE SALESREP
ADD JOBCODE VARCHAR(12);

DESCRIBE SALESREP;

ALTER TABLE SALESREP
MODIFY SALARY NOT NULL;

ALTER TABLE GOODCUST
MODIFY LOCATION NULL;

DESCRIBE GOODCUST;

ALTER TABLE SALESREP
MODIFY FNAME VARCHAR(37);

SELECT MAX(LENGTH(NAME)) FROM GOODCUST;
ALTER TABLE GOODCUST
MODIFY NAME VARCHAR(17);

ALTER TABLE SALESREP
SET UNUSED(JOBCODE);

ALTER TABLE SALESREP
ADD CONSTRAINT SALES_REP_PHONE_NAME_UK UNIQUE(PHONE_NUMBER, FNAME, LNAME);

DESCRIBE SALESREP;

ALTER TABLE SALESREP
MODIFY CONSTRAINT SALESREP_SALARY_CK CHECK(SALARY IN (BETWEEEN 5000 TO 15000));
ALTER TABLE SALESREP
ADD CONSTRAINT SALESREP_COMMISION_CK CHECK(COMMISSION < 0.5);

SELECT * FROM SALESREP;

ALTER TABLE SALESREP
ADD CONSTRAINT SALESREP_SALARY_CK CHECK(SALARY >= 5000 AND SALARY <= 15000);

ALTER TABLE SALESREP
DROP CONSTRAINT SALESREP_SALARY_CK;


SELECT  constraint_name, constraint_type, search_condition, table_name
FROM     user_constraints       
WHERE table_name IN ('SALESREP','GOODCUST')
ORDER  BY  4 , 2

