SET LINESIZE 1000;
SET PAGESIZE 200;

--question 5A
SELECT 
    D.DEPARTMENT_NAME,
    L.CITY,
    L.STREET_ADDRESS,
    L.POSTAL_CODE
FROM DEPARTMENTS D, LOCATIONS L  
WHERE D.LOCATION_ID = L.LOCATION_ID
ORDER BY L.CITY, D.DEPARTMENT_NAME;


SELECT
    E.LAST_NAME || ', ' ||E.FIRST_NAME AS "FULL NAME",
    E.HIRE_DATE,
    E.SALARY,
    D.DEPARTMENT_NAME,
    L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND SUBSTR(D.DEPARTMENT_NAME,1,1) IN ('A','S')
ORDER BY 4, 1;

SELECT
       D.DEPARTMENT_NAME,
       E.LAST_NAME || ', ' ||E.FIRST_NAME AS "MANAGER NAME",
       L.CITY,
       L.POSTAL_CODE,
       L.STATE_PROVINCE
FROM   DEPARTMENTS D LEFT JOIN  EMPLOYEES E
ON     D.MANAGER_ID = E.EMPLOYEE_ID
JOIN   LOCATIONS L
ON     D.LOCATION_ID = L.LOCATION_ID
AND  L.STATE_PROVINCE IN ('Ontario', 'California', 'Washington')
ORDER BY L.CITY, D.DEPARTMENT_NAME;

SELECT 
      E.LAST_NAME "Employee",
      E.EMPLOYEE_ID "Emp#",
      M.LAST_NAME "Manager",
      M.MANAGER_ID "Mgr#"
FROM EMPLOYEES E JOIN EMPLOYEES M
ON  E.MANAGER_ID = M.EMPLOYEE_ID;

--question 5B
SELECT
    LOCATION_ID,
    STREET_ADDRESS,
    CITY,
    STATE_PROVINCE,
    COUNTRY_NAME
FROM LOCATIONS L LEFT JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID;


SELECT 
    EMPLOYEE_ID,
    LAST_NAME,
    JOB_ID,
    DEPARTMENT_NAME,
    GRADE
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON   E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN JOB_GRADES
ON E.SALARY BETWEEN LOWEST_SAL AND HIGHEST_SAL;

SELECT
    E.EMPLOYEE_ID,
    E.LAST_NAME, 
    M.LAST_NAME "MANAGER",
    M.EMPLOYEE_ID "M EMPLOYEE ID"
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
ON  E.MANAGER_ID = M.EMPLOYEE_ID;
    

SELECT
      LAST_NAME,
      FIRST_NAME,
      CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;


SELECT
     CITY,
     LAST_NAME,
     FIRST_NAME
FROM LOCATIONS L JOIN DEPARTMENTS D
ON L.LOCATION_ID = D.LOCATION_ID
JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

--QUESTION 5B -4
SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    DEPARTMENT_NAME,
    CITY
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
JOIN LOCATIONS USING (LOCATION_ID);


SELECT
     LAST_NAME,
     FIRST_NAME,
     CITY
FROM LOCATIONS L FULL OUTER JOIN DEPARTMENTS D
ON L.LOCATION_ID = D.LOCATION_ID
FULL OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;


