CREATE TABLE DIVISION(
DIVISION_ID NUMBER(3),
DIVISION_NAME VARCHAR(25) NOT NULL UNIQUE,
CONSTRAINT DIVISION_DIVISION_ID_PK
PRIMARY KEY(DIVISION_ID));


CREATE TABLE WAREHOUSE(
WAREHOUSE_ID  NUMBER(3),
CITY          VARCHAR(15) NOT NULL UNIQUE,
RATING        CHAR(1) 
              CONSTRAINT WAREHOUSE_RATING_CHECK CHECK(RATING IN ('A','B','C','D')),
FOUND_DATE    DATE NOT NULL,
DIVISION_ID   NUMBER(3) NOT NULL,
CONSTRAINT WAREHOUSE_WAREHOUSE_ID_PK
      PRIMARY KEY(WAREHOUSE_ID),
CONSTRAINT WAREHOUSE_DIVISION_ID_FK
       FOREIGN KEY(DIVISION_ID)
       REFERENCES DIVISION(DIVISION_ID));
       
CREATE TABLE SECTION(
  WAREHOUSE_ID NUMBER(3),
  SECTION_ID NUMBER(2),
  DESCRIPTION VARCHAR(50) NOT NULL,
  CAPACITY NUMBER(8),
  CONSTRAINT SECTION_WAREHOUSE_ID_FK
        FOREIGN KEY(WAREHOUSE_ID)
        REFERENCES WAREHOUSE(WAREHOUSE_ID),
  CONSTRAINT SECTION_COMPOSITE_PK
        PRIMARY KEY(WAREHOUSE_ID, SECTION_ID));
        
ALTER TABLE SECTION
  ADD MGR_ID NUMBER(6)
    CONSTRAINT SECTION_MGR_ID_FK
    REFERENCES EMPLOYEES(EMPLOYEE_ID);
    
ALTER TABLE WAREHOUSE
  DROP CONSTRAINT WAREHOUSE_RATING_CHECK;
ALTER TABLE WAREHOUSE  
  ADD CONSTRAINT WAREHOUSE_RATING_CHECK 
       CHECK(RATING IN ('A','B','C','D','F'));
       
       
CREATE SEQUENCE WHSE_ID_SEQ
  INCREMENT BY 10
  START WITH 410
  MAXVALUE  700
  NOCYCLE
  NOCACHE;

DROP SEQUENCE WHSE_ID_SEQ;

SELECT * FROM DIVISION;  

INSERT INTO DIVISION VALUES(10,'Europe');

SELECT * FROM DIVISION;  
SELECT * FROM WAREHOUSE;  
DELETE FROM WAREHOUSE;
INSERT INTO WAREHOUSE (WAREHOUSE_ID, CITY, RATING, FOUND_DATE,DIVISION_ID)
            VALUES(WHSE_ID_SEQ.NEXTVAL,'Atlanta','A',SYSDATE,10);
            
CREATE TABLE CITIES AS
(SELECT * FROM LOCATIONS WHERE LOCATION_ID < 2000);

SELECT * FROM CITIES;

DESCRIBE CITIES;

SET PAGESIZE 100;
SET LINESIZE 500;

SELECT * FROM SECTION;

INSERT INTO SECTION VALUES(410,10,'Warehouse Name',500,201);

CREATE VIEW WHSSEC_MAN_VU AS(
  SELECT WAREHOUSE_ID, 
         SECTION_ID, 
         CITY, 
         DIVISION_NAME AS "GROUP",
        LAST_NAME AS "LName"
  FROM WAREHOUSE JOIN SECTION USING(WAREHOUSE_ID)
  JOIN DIVISION USING(DIVISION_ID)
  JOIN EMPLOYEES
  ON MGR_ID = EMPLOYEE_ID
);
 
 SELECT 1 FROM sys.views WHERE name = 'WHSSEC_MAN_VU';
 
 select view_name from user_views;
 
 SELECT *  FROM USER_VIEWS;

SELECT * FROM WHSSEC_MAN_VU;

SELECT * FROM LOCATIONS
MINUS
SELECT * FROM CITIES;
            