SELECT AVG(SALARY) - MIN(SALARY) AS "Real Amount"
FROM EMPLOYEES;


SELECT 
    DEPARTMENT_ID,
    MAX(SALARY) AS "High",
    MIN(SALARY) AS "Low",
    ROUND(AVG(SALARY)) AS "Avg"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 3 DESC;

SELECT 
  DEPARTMENT_ID AS "Dept#",
  JOB_ID AS "Job",
  COUNT(JOB_ID) AS "How Many"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING COUNT(JOB_ID) > 1
ORDER BY 3 DESC;

SELECT 
    JOB_ID,
    SUM(SALARY) AS "Total Paid Monthly"
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING JOB_ID NOT IN ('AD_PRES','AD_VP')
AND SUM(SALARY) > 15000
ORDER BY 2 DESC;

SELECT 
  DEPARTMENT_ID,
  MANAGER_ID,
  COUNT(MANAGER_ID) as "Total Employee"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, MANAGER_ID
HAVING MANAGER_ID NOT IN (100,101,102)
AND COUNT(MANAGER_ID) > 2;


SELECT 
       DEPARTMENT_ID,
       MIN(HIRE_DATE) AS "Earliest",
       MAX(HIRE_DATE) AS "Latest"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID NOT IN (10,20)
AND TO_CHAR(MAX(HIRE_DATE), 'CC') != TO_CHAR(SYSDATE,'CC')
ORDER BY 3 DESC;


